using IFactory.UI.Controls;
using IFactory.UI.Core;
using IFactory.Domain.Models;
using IFactory.Platform.Common.Request;
using IFactory.Platform.Common.Request.Product;
using IFactory.Platform.Common.Response.Product;
using System;
using System.CodeDom.Compiler;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Markup;

namespace IFactory.UI.CraftDetails
{
    /// <summary>
    /// CraftDetailPage3.xaml 的交互逻辑
    /// </summary>
    public partial class CraftDetailPage3 : BaseCraftDetailPage, IComponentConnector
    {
        public CraftDetailPage3()
        {
            InitializeComponent();
        }

        private void BaseCraftDetailPage_Loaded(object sender, RoutedEventArgs e)
        {
            int num1 = 1;
            List<FieldRow> fieldRowList1 = new List<FieldRow>();
            List<FieldRow> fieldRowList2 = fieldRowList1;
            FieldRow fieldRow1 = new FieldRow();
            int num2 = num1;
            int num3 = 1;
            int num4 = num2 + num3;
            fieldRow1.Iden = num2;
            string str1 = "工厂";
            fieldRow1.FieldName = str1;
            string str2 = "";
            fieldRow1.FieldValue = str2;
            fieldRowList2.Add(fieldRow1);
            List<FieldRow> fieldRowList3 = fieldRowList1;
            FieldRow fieldRow2 = new FieldRow();
            int num5 = num4;
            int num6 = 1;
            int num7 = num5 + num6;
            fieldRow2.Iden = num5;
            string str3 = "设备名称";
            fieldRow2.FieldName = str3;
            string str4 = "";
            fieldRow2.FieldValue = str4;
            fieldRowList3.Add(fieldRow2);
            List<FieldRow> fieldRowList4 = fieldRowList1;
            FieldRow fieldRow3 = new FieldRow();
            int num8 = num7;
            int num9 = 1;
            int num10 = num8 + num9;
            fieldRow3.Iden = num8;
            string str5 = "设备IP地址";
            fieldRow3.FieldName = str5;
            string str6 = "";
            fieldRow3.FieldValue = str6;
            fieldRowList4.Add(fieldRow3);
            List<FieldRow> fieldRowList5 = fieldRowList1;
            FieldRow fieldRow4 = new FieldRow();
            int num11 = num10;
            int num12 = 1;
            int num13 = num11 + num12;
            fieldRow4.Iden = num11;
            string str7 = "设备PLC端口";
            fieldRow4.FieldName = str7;
            string str8 = "";
            fieldRow4.FieldValue = str8;
            fieldRowList5.Add(fieldRow4);
            List<FieldRow> fieldRowList6 = fieldRowList1;
            FieldRow fieldRow5 = new FieldRow();
            int num14 = num13;
            int num15 = 1;
            int num16 = num14 + num15;
            fieldRow5.Iden = num14;
            string str9 = "MMAddress";
            fieldRow5.FieldName = str9;
            string str10 = "";
            fieldRow5.FieldValue = str10;
            fieldRowList6.Add(fieldRow5);
            List<FieldRow> fieldRowList7 = fieldRowList1;
            FieldRow fieldRow6 = new FieldRow();
            int num17 = num16;
            int num18 = 1;
            int num19 = num17 + num18;
            fieldRow6.Iden = num17;
            string str11 = "MMAddressNO";
            fieldRow6.FieldName = str11;
            string str12 = "";
            fieldRow6.FieldValue = str12;
            fieldRowList7.Add(fieldRow6);
            List<FieldRow> fieldRowList8 = fieldRowList1;
            FieldRow fieldRow7 = new FieldRow();
            int num20 = num19;
            int num21 = 1;
            int num22 = num20 + num21;
            fieldRow7.Iden = num20;
            string str13 = "设备启用";
            fieldRow7.FieldName = str13;
            string str14 = "";
            fieldRow7.FieldValue = str14;
            fieldRowList8.Add(fieldRow7);
            List<FieldRow> fieldRowList9 = fieldRowList1;
            FieldRow fieldRow8 = new FieldRow();
            int num23 = num22;
            int num24 = 1;
            int num25 = num23 + num24;
            fieldRow8.Iden = num23;
            string str15 = "设备清除报警地址";
            fieldRow8.FieldName = str15;
            string str16 = "";
            fieldRow8.FieldValue = str16;
            fieldRowList9.Add(fieldRow8);
            List<FieldRow> fieldRowList10 = fieldRowList1;
            FieldRow fieldRow9 = new FieldRow();
            int num26 = num25;
            int num27 = 1;
            int num28 = num26 + num27;
            fieldRow9.Iden = num26;
            string str17 = "设备重置地址";
            fieldRow9.FieldName = str17;
            string str18 = "";
            fieldRow9.FieldValue = str18;
            fieldRowList10.Add(fieldRow9);
            this.dataGrid1.ItemsSource = fieldRowList1;
            List<FieldRow> fieldRowList11 = new List<FieldRow>();
            List<FieldRow> fieldRowList12 = fieldRowList11;
            FieldRow fieldRow10 = new FieldRow();
            int num29 = num28;
            int num30 = 1;
            int num31 = num29 + num30;
            fieldRow10.Iden = num29;
            string str19 = "PLC信号地址";
            fieldRow10.FieldName = str19;
            string str20 = "";
            fieldRow10.FieldValue = str20;
            fieldRowList12.Add(fieldRow10);
            List<FieldRow> fieldRowList13 = fieldRowList11;
            FieldRow fieldRow11 = new FieldRow();
            int num32 = num31;
            int num33 = 1;
            int num34 = num32 + num33;
            fieldRow11.Iden = num32;
            string str21 = "MMEndAddr";
            fieldRow11.FieldName = str21;
            string str22 = "";
            fieldRow11.FieldValue = str22;
            fieldRowList13.Add(fieldRow11);
            List<FieldRow> fieldRowList14 = fieldRowList11;
            FieldRow fieldRow12 = new FieldRow();
            int num35 = num34;
            int num36 = 1;
            int num37 = num35 + num36;
            fieldRow12.Iden = num35;
            string str23 = "MMCountAddr";
            fieldRow12.FieldName = str23;
            string str24 = "";
            fieldRow12.FieldValue = str24;
            fieldRowList14.Add(fieldRow12);
            List<FieldRow> fieldRowList15 = fieldRowList11;
            FieldRow fieldRow13 = new FieldRow();
            int num38 = num37;
            int num39 = 1;
            int num40 = num38 + num39;
            fieldRow13.Iden = num38;
            string str25 = "MMBadAddr";
            fieldRow13.FieldName = str25;
            string str26 = "";
            fieldRow13.FieldValue = str26;
            fieldRowList15.Add(fieldRow13);
            List<FieldRow> fieldRowList16 = fieldRowList11;
            FieldRow fieldRow14 = new FieldRow();
            int num41 = num40;
            int num42 = 1;
            int num43 = num41 + num42;
            fieldRow14.Iden = num41;
            string str27 = "MMRemark";
            fieldRow14.FieldName = str27;
            string str28 = "";
            fieldRow14.FieldValue = str28;
            fieldRowList16.Add(fieldRow14);
            List<FieldRow> fieldRowList17 = fieldRowList11;
            FieldRow fieldRow15 = new FieldRow();
            int num44 = num43;
            int num45 = 1;
            int num46 = num44 + num45;
            fieldRow15.Iden = num44;
            string str29 = "设备顺序号";
            fieldRow15.FieldName = str29;
            string str30 = "";
            fieldRow15.FieldValue = str30;
            fieldRowList17.Add(fieldRow15);
            List<FieldRow> fieldRowList18 = fieldRowList11;
            FieldRow fieldRow16 = new FieldRow();
            int num47 = num46;
            int num48 = 1;
            int num49 = num47 + num48;
            fieldRow16.Iden = num47;
            string str31 = "采集地址";
            fieldRow16.FieldName = str31;
            string str32 = "";
            fieldRow16.FieldValue = str32;
            fieldRowList18.Add(fieldRow16);
            List<FieldRow> fieldRowList19 = fieldRowList11;
            FieldRow fieldRow17 = new FieldRow();
            int num50 = num49;
            int num51 = 1;
            int num52 = num50 + num51;
            fieldRow17.Iden = num50;
            string str33 = "采集类型";
            fieldRow17.FieldName = str33;
            string str34 = "";
            fieldRow17.FieldValue = str34;
            fieldRowList19.Add(fieldRow17);
            List<FieldRow> fieldRowList20 = fieldRowList11;
            FieldRow fieldRow18 = new FieldRow();
            int num53 = num52;
            int num54 = 1;
            int num55 = num53 + num54;
            fieldRow18.Iden = num53;
            string str35 = "是否启用（数据采集）";
            fieldRow18.FieldName = str35;
            string str36 = "";
            fieldRow18.FieldValue = str36;
            fieldRowList20.Add(fieldRow18);
            List<FieldRow> fieldRowList21 = fieldRowList11;
            FieldRow fieldRow19 = new FieldRow();
            int num56 = num55;
            int num57 = 1;
            int num58 = num56 + num57;
            fieldRow19.Iden = num56;
            string str37 = "Remark";
            fieldRow19.FieldName = str37;
            string str38 = "";
            fieldRow19.FieldValue = str38;
            fieldRowList21.Add(fieldRow19);
            this.dataGrid2.ItemsSource = fieldRowList11;
            this.ddlFacility.ItemsSource = ( LocalApi.Execute(new FacilityListRequest()
            {
                CraftDID = this.CraftDID
            })).Facilities;
        }

        private void BuildRows(FacilityModel model)
        {
            int num1 = 1;
            List<FieldRow> fieldRowList1 = new List<FieldRow>();
            List<FieldRow> fieldRowList2 = fieldRowList1;
            FieldRow fieldRow1 = new FieldRow();
            int num2 = num1;
            int num3 = 1;
            int num4 = num2 + num3;
            fieldRow1.Iden = num2;
            string str1 = "工厂";
            fieldRow1.FieldName = str1;
            string str2 = "";
            fieldRow1.FieldValue = str2;
            fieldRowList2.Add(fieldRow1);
            List<FieldRow> fieldRowList3 = fieldRowList1;
            FieldRow fieldRow2 = new FieldRow();
            int num5 = num4;
            int num6 = 1;
            int num7 = num5 + num6;
            fieldRow2.Iden = num5;
            string str3 = "设备名称";
            fieldRow2.FieldName = str3;
            string mmName = model.MMName;
            fieldRow2.FieldValue = mmName;
            fieldRowList3.Add(fieldRow2);
            List<FieldRow> fieldRowList4 = fieldRowList1;
            FieldRow fieldRow3 = new FieldRow();
            int num8 = num7;
            int num9 = 1;
            int num10 = num8 + num9;
            fieldRow3.Iden = num8;
            string str4 = "设备IP地址";
            fieldRow3.FieldName = str4;
            string mmip = model.MMIP;
            fieldRow3.FieldValue = mmip;
            fieldRowList4.Add(fieldRow3);
            List<FieldRow> fieldRowList5 = fieldRowList1;
            FieldRow fieldRow4 = new FieldRow();
            int num11 = num10;
            int num12 = 1;
            int num13 = num11 + num12;
            fieldRow4.Iden = num11;
            string str5 = "设备PLC端口";
            fieldRow4.FieldName = str5;
            string mmPort = model.MMPort;
            fieldRow4.FieldValue = mmPort;
            fieldRowList5.Add(fieldRow4);
            List<FieldRow> fieldRowList6 = fieldRowList1;
            FieldRow fieldRow5 = new FieldRow();
            int num14 = num13;
            int num15 = 1;
            int num16 = num14 + num15;
            fieldRow5.Iden = num14;
            string str6 = "MMAddress";
            fieldRow5.FieldName = str6;
            string maAddress = model.MAAddress;
            fieldRow5.FieldValue = maAddress;
            fieldRowList6.Add(fieldRow5);
            List<FieldRow> fieldRowList7 = fieldRowList1;
            FieldRow fieldRow6 = new FieldRow();
            int num17 = num16;
            int num18 = 1;
            int num19 = num17 + num18;
            fieldRow6.Iden = num17;
            string str7 = "MMAddressNO";
            fieldRow6.FieldName = str7;
            string str8 = "";
            fieldRow6.FieldValue = str8;
            fieldRowList7.Add(fieldRow6);
            List<FieldRow> fieldRowList8 = fieldRowList1;
            FieldRow fieldRow7 = new FieldRow();
            int num20 = num19;
            int num21 = 1;
            int num22 = num20 + num21;
            fieldRow7.Iden = num20;
            string str9 = "设备启用";
            fieldRow7.FieldName = str9;
            string str10 = "";
            fieldRow7.FieldValue = str10;
            fieldRowList8.Add(fieldRow7);
            List<FieldRow> fieldRowList9 = fieldRowList1;
            FieldRow fieldRow8 = new FieldRow();
            int num23 = num22;
            int num24 = 1;
            int num25 = num23 + num24;
            fieldRow8.Iden = num23;
            string str11 = "设备清除报警地址";
            fieldRow8.FieldName = str11;
            string str12 = "";
            fieldRow8.FieldValue = str12;
            fieldRowList9.Add(fieldRow8);
            List<FieldRow> fieldRowList10 = fieldRowList1;
            FieldRow fieldRow9 = new FieldRow();
            int num26 = num25;
            int num27 = 1;
            int num28 = num26 + num27;
            fieldRow9.Iden = num26;
            string str13 = "设备重置地址";
            fieldRow9.FieldName = str13;
            string mmClearAddr = model.MMClearAddr;
            fieldRow9.FieldValue = mmClearAddr;
            fieldRowList10.Add(fieldRow9);
            this.dataGrid1.ItemsSource = fieldRowList1;
            List<FieldRow> fieldRowList11 = new List<FieldRow>();
            List<FieldRow> fieldRowList12 = fieldRowList11;
            FieldRow fieldRow10 = new FieldRow();
            int num29 = num28;
            int num30 = 1;
            int num31 = num29 + num30;
            fieldRow10.Iden = num29;
            string str14 = "PLC信号地址";
            fieldRow10.FieldName = str14;
            string str15 = "";
            fieldRow10.FieldValue = str15;
            fieldRowList12.Add(fieldRow10);
            List<FieldRow> fieldRowList13 = fieldRowList11;
            FieldRow fieldRow11 = new FieldRow();
            int num32 = num31;
            int num33 = 1;
            int num34 = num32 + num33;
            fieldRow11.Iden = num32;
            string str16 = "MMEndAddr";
            fieldRow11.FieldName = str16;
            string str17 = "";
            fieldRow11.FieldValue = str17;
            fieldRowList13.Add(fieldRow11);
            List<FieldRow> fieldRowList14 = fieldRowList11;
            FieldRow fieldRow12 = new FieldRow();
            int num35 = num34;
            int num36 = 1;
            int num37 = num35 + num36;
            fieldRow12.Iden = num35;
            string str18 = "MMCountAddr";
            fieldRow12.FieldName = str18;
            string str19 = "";
            fieldRow12.FieldValue = str19;
            fieldRowList14.Add(fieldRow12);
            List<FieldRow> fieldRowList15 = fieldRowList11;
            FieldRow fieldRow13 = new FieldRow();
            int num38 = num37;
            int num39 = 1;
            int num40 = num38 + num39;
            fieldRow13.Iden = num38;
            string str20 = "MMBadAddr";
            fieldRow13.FieldName = str20;
            string str21 = "";
            fieldRow13.FieldValue = str21;
            fieldRowList15.Add(fieldRow13);
            List<FieldRow> fieldRowList16 = fieldRowList11;
            FieldRow fieldRow14 = new FieldRow();
            int num41 = num40;
            int num42 = 1;
            int num43 = num41 + num42;
            fieldRow14.Iden = num41;
            string str22 = "MMRemark";
            fieldRow14.FieldName = str22;
            string str23 = "";
            fieldRow14.FieldValue = str23;
            fieldRowList16.Add(fieldRow14);
            List<FieldRow> fieldRowList17 = fieldRowList11;
            FieldRow fieldRow15 = new FieldRow();
            int num44 = num43;
            int num45 = 1;
            int num46 = num44 + num45;
            fieldRow15.Iden = num44;
            string str24 = "设备顺序号";
            fieldRow15.FieldName = str24;
            string str25 = "";
            fieldRow15.FieldValue = str25;
            fieldRowList17.Add(fieldRow15);
            List<FieldRow> fieldRowList18 = fieldRowList11;
            FieldRow fieldRow16 = new FieldRow();
            int num47 = num46;
            int num48 = 1;
            int num49 = num47 + num48;
            fieldRow16.Iden = num47;
            string str26 = "采集地址";
            fieldRow16.FieldName = str26;
            string str27 = "";
            fieldRow16.FieldValue = str27;
            fieldRowList18.Add(fieldRow16);
            List<FieldRow> fieldRowList19 = fieldRowList11;
            FieldRow fieldRow17 = new FieldRow();
            int num50 = num49;
            int num51 = 1;
            int num52 = num50 + num51;
            fieldRow17.Iden = num50;
            string str28 = "采集类型";
            fieldRow17.FieldName = str28;
            string str29 = "";
            fieldRow17.FieldValue = str29;
            fieldRowList19.Add(fieldRow17);
            List<FieldRow> fieldRowList20 = fieldRowList11;
            FieldRow fieldRow18 = new FieldRow();
            int num53 = num52;
            int num54 = 1;
            int num55 = num53 + num54;
            fieldRow18.Iden = num53;
            string str30 = "是否启用（数据采集）";
            fieldRow18.FieldName = str30;
            string str31 = "";
            fieldRow18.FieldValue = str31;
            fieldRowList20.Add(fieldRow18);
            List<FieldRow> fieldRowList21 = fieldRowList11;
            FieldRow fieldRow19 = new FieldRow();
            int num56 = num55;
            int num57 = 1;
            int num58 = num56 + num57;
            fieldRow19.Iden = num56;
            string str32 = "Remark";
            fieldRow19.FieldName = str32;
            string str33 = "";
            fieldRow19.FieldValue = str33;
            fieldRowList21.Add(fieldRow19);
            this.dataGrid2.ItemsSource = fieldRowList11;
        }

        private void ddlFacility_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            this.BuildRows(((IList<FacilityModel>)this.ddlFacility.ItemsSource)[this.ddlFacility.SelectedIndex]);
        }
    }
}
